### ISSUE TITLE
fatal: repository 'https://github.com/NodLabs/SHARK/tree/main/iree/' not found

### ISSUE THREAD

**Issue by liu-shaobo** [mmperf/mmperf#72]
hi ，clone iree error，how can I solve it?

Cloning into '/root/mmperf/external/flatbuffers'...
remote: Enumerating objects: 25292, done.
remote: Counting objects: 100% (2168/2168), done.
remote: Compressing objects: 100% (890/890), done.
remote: Total 25292 (delta 1329), reused 1818 (delta 1174), pack-reused 23124
Receiving objects: 100% (25292/25292), 15.85 MiB | 13.83 MiB/s, done.
Resolving deltas: 100% (17583/17583), done.
Cloning into '/root/mmperf/external/iree'...
**fatal: repository 'https://github.com/NodLabs/SHARK/tree/main/iree/' not found
fatal: clone of 'https://github.com/NodLabs/SHARK/tree/main/iree' into submodule path '/root/mmperf/external/iree' failed**
Failed to clone 'external/iree'. Retry scheduled
Cloning into '/root/mmperf/external/iree-llvm-sandbox'...
remote: Enumerating objects: 7480, done.
remote: Counting objects: 100% (7480/7480), done.
remote: Compressing objects: 100% (2161/2161), done.
remote: Total 7480 (delta 5395), reused 7135 (delta 5153), pack-reused 0
Receiving objects: 100% (7480/7480), 2.98 MiB | 4.22 MiB/s, done.
Resolving deltas: 100% (5395/5395), done.

**Comment by powderluv** [comment]
@yzhang93  looks like an error in the submodule

As a workaround please edit the .gitmodules file to just point to nodlabs/SHARK and remove the branch

**Comment by liu-shaobo** [comment]
thank you，Can be solved

**Comment by powderluv** [comment]
I pushed a patch to fix this. thanks for the report.
